services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Production
      - GitHub__ClientId=${GitHub__ClientId}
      - GitHub__ClientSecret=${GitHub__ClientSecret}
      - GitHub__RedirectUri=${GitHub__RedirectUri}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
